
wandb: WARNING Calling run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
Time taken for epoch: 7625.024960041046 seconds
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Users\z003zv1a\Anaconda3\envs\py3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\z003zv1a\Anaconda3\envs\py3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\z003zv1a\Anaconda3\envs\py3\lib\site-packages\wandb\sdk\wandb_run.py", line 183, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "C:\Users\z003zv1a\Anaconda3\envs\py3\lib\site-packages\wandb\sdk\interface\interface.py", line 755, in communicate_network_status
    resp = self._communicate(req, timeout=timeout, local=True)
  File "C:\Users\z003zv1a\Anaconda3\envs\py3\lib\site-packages\wandb\sdk\interface\interface.py", line 545, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\z003zv1a\Anaconda3\envs\py3\lib\site-packages\wandb\sdk\interface\interface.py", line 550, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
